//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamen_Natillera
    {
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public string Afiliado { get; set; }
        public System.DateTime FechaCredito { get; set; }
        public int ValorCredito { get; set; }
        public int PlazoCredito { get; set; }
        public float PorcentajeCredito { get; set; }
        public int CuotaMensualIntereses { get; set; }
    }
}
