//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOtaCRedito
    {
        public int Numero { get; set; }
        public int CodigoDevolucion { get; set; }
        public int Valor { get; set; }
        public System.DateTime FechaValidez { get; set; }
    }
}
