//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaEscenario
    {
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public int HorasReserva { get; set; }
        public string DiaReserva { get; set; }
        public int ValorSinDescuento { get; set; }
        public int ValorDescuento { get; set; }
        public int ValorPagar { get; set; }
    }
}
