//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Perfil
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idPerfil { get; set; }
        public bool Activo { get; set; }

        [JsonIgnore]
        public virtual Perfil Perfil { get; set; }
        [JsonIgnore]
        public virtual Usuario Usuario { get; set; }
    }
}
